language: php

php:
  - "7.0"
  - "7.1"
  - "hhvm"

cache:
  directories:
    - $HOME/.composer/cache

install: composer install

script: 
- vendor/bin/phpcs --standard=ruleset.xml
- vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/coveralls
